name: Deploy WebAssembly binary.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build the WebAssembly binary in the jspanchu/vtk-wasm-target container
      run: |
        mkdir build
        docker run \
        -v ${{ github.workspace }}:/project/src -v ${{ github.workspace }}/build:/project/build \
        jspanchu/vtk-wasm-target:latest /bin/bash -c \
        "emcmake cmake -GNinja -S /project/src -B /project/build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF && \
        cmake --build /project/build && \
        mv /project/build/*.js /project/src/ && \
        mv /project/build/*.wasm /project/src && \
        rm -rf /project/build"
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Deploy WebAssembly binaries"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
